### ISSUE TITLE
'buffertools.node' was compiled against a different Node.js version using

### ISSUE THREAD

**Issue by Serveurperso** [mmaelzer/mjpeg-consumer#15]
Hello

I can use mjpeg-consumer on my intel but not on raspberry PI
I already tested `npm rebuild` or `npm install` without success :

```
/var/www/node_modules/mjpeg-consumer/node_modules/buffertools/buffertools.js:26
        if (e.code !== 'MODULE_NOT_FOUND') throw e;
                                           ^

Error: The module '/var/www/node_modules/mjpeg-consumer/node_modules/buffertools/build/Release/buffertools.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:602:18)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/node_modules/mjpeg-consumer/node_modules/buffertools/buffertools.js:24:20)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)


(root|/var/www) nodejs serveurrobot.js
/var/www/node_modules/serialport/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: Module version mismatch. Expected 46, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/var/www/node_modules/serialport/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/var/www/node_modules/serialport/lib/bindings/linux.js:2:36)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)



(root|/var/www) node -v
v8.4.0
(root|/var/www) nodejs -v
v4.8.2
(root|/var/www) npm -v
1.4.21


```
npm rebuild do not work !!!

Can you help to solve this ?

Thanks
Pascal

**Comment by Serveurperso** [comment]
SOLVED !
I must remove manualy the build directory before the "npm rebuild"
```
rm -rf /var/www/node_modules/mjpeg-consumer/node_modules/buffertools/build/
npm rebuild
```
It's strange because I removed the entire "node_modules" directory many time without success.
But now it work:D

**Comment by mmaelzer** [comment]
Glad you were able to solve the issue! Closing this issue.
